//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Zen++.rc
//
#define ACCELERATOR_ZENPP               10
#define BITMAP_FIRMWARE_STEP1           20
#define BITMAP_FIRMWARE_STEP2           21
#define BUTTON_ABOUT_OK                 100
#define BUTTON_FIRMWARE_BACK            101
#define BUTTON_FIRMWARE_CANCEL          102
#define BUTTON_FIRMWARE_NEXT            103
#define BUTTON_MAIN_ADDSCRIPT           110
#define BUTTON_MAIN_ERASEALLSCRIPTS     111
#define BUTTON_MAIN_FACTORYRESET        112
#define BUTTON_MAIN_PROGRAMDEVICE       113
#define BUTTON_MAIN_REMOVESELECTION     114
#define BUTTON_MAIN_SOFTRESET           115
#define MENU_MKSETTINGS                 129
#define IDR_FILE1                       137
#define FILE_ZPPUPDATER                 137
#define DIALOG_ABOUT                    200
#define DIALOG_CODE                     201
#define DIALOG_FIRMWARE                 202
#define DIALOG_MAIN                     203
#define DIALOG_MKSETTINGS               204
#define EDIT_ABOUT_INFORMATION          300
#define EDIT_FIRMWARE_DESCRIPTORS       310
#define EDIT_MKSETTINGS_PROFILENAME     320
#define EDIT_MKSETTINGS_VERSION         321
#define EDIT_MAIN_SLOTS                 330
#define FILE_FIRMWARE_COMPATIBLE        400
#define FILE_FIRMWARE_LATEST            401
#define ICON_ZENPP                      500
#define LABEL_ABOUT_HEADER              600
#define LABEL_ABOUT_VERSIONINFO         601
#define LABEL_FIRMWARE_INSTRUCTIONS     610
#define LABEL_FIRMWARE_STATUS           611
#define LABEL_FIRMWARE_STEP             612
#define LABEL_MKSETTINGS_CONFIG         620
#define LABEL_MKSETTINGS_GAMEPROFILE    621
#define LABEL_MKSETTINGS_PROFILENAME    622
#define LABEL_MKSETTINGS_VERSION        623
#define LIST_MAIN_SLOTS                 700
#define MENU_CONNECTION_CONNECTONSTARTUP 800
#define MENU_CONNECTION_DISCONNECT      801
#define MENU_CONNECTION_LOWPERFORMANCEMODE 802
#define MENU_CONNECTION_RECONNECT       803
#define MENU_DEVICE_CLEARBLUETOOTHDEVICES 810
#define MENU_DEVICE_CYCLESLOTS          811
#define MENU_DEVICE_EOP_AUTO            820
#define MENU_DEVICE_EOP_NINTENDOSWITCH  821
#define MENU_DEVICE_EOP_PCMOBILEXBOX360 822
#define MENU_DEVICE_EOP_PLAYSTATION3    823
#define MENU_DEVICE_EOP_PLAYSTATION4    824
#define MENU_DEVICE_EOP_XBOXONEX        825
#define MENU_DEVICE_OM_NORMAL           830
#define MENU_DEVICE_OM_TOURNAMENT       831
#define MENU_DEVICE_OM_WHEEL            832
#define MENU_DEVICE_PROGRAMDEVICE       840
#define MENU_DEVICE_PS4SPECIALTY        850
#define MENU_DEVICE_REFRESHATTACHEDDEVICES 860
#define MENU_DEVICE_REMOTEPLAY          870
#define MENU_DEVICE_RSC_DISABLED        880
#define MENU_DEVICE_RSC_PSL3            881
#define MENU_DEVICE_RSC_PSSHARE         882
#define MENU_DEVICE_TURNOFFCONTROLLER   890
#define MENU_FILE_EXIT                  900
#define MENU_FILE_NEW                   901
#define MENU_FILE_NEWLAYOUT             902
#define MENU_FILE_SAVELAYOUT            903
#define MENU_FILE_EXPORTLAYOUT          904
#define MENU_FILE_IMPORTLAYOUT          905
#define MENU_FIRMWARE_COMPATIBLE        910
#define MENU_FIRMWARE_CUSTOM            911
#define MENU_FIRMWARE_ERASE             912
#define MENU_FIRMWARE_LATEST            913
#define MENU_HELP_ABOUT                 920
#define MENU_HELP_CHANGELOG             921
#define MENU_HELP_NEWS                  922
#define MENU_HELP_ZENPPNEWS             923
#define MENU_LISTBOX_POPUP              930
#define MENU_LISTBOX_POPUP_EXPORTBIN    931
#define MENU_LISTBOX_POPUP_EXPORTSETTINGS 932
#define MENU_LISTBOX_POPUP_IMPORTSETTINGS 933
#define MENU_LISTBOX_POPUP_MOVEDOWN     934
#define MENU_LISTBOX_POPUP_MOVEUP       935
#define MENU_LISTBOX_POPUP_REMOVE       936
#define MENU_MAIN                       940
#define MENU_POPUP_CLEAR                950
#define MENU_POPUP_COPY                 951
#define MENU_POPUP_SELECTALL            952
#define MENU_RICHEDIT_POPUP             960
#define MENU_VIEW_24HOURTIMESTAMPS      970
#define MENU_VIEW_BINLIB                971
#define MENU_VIEW_BLACKBACKGROUND       972
#define MENU_VIEW_CONNECTIONTRACE       973
#define MENU_VIEW_DEVICEMONITOR         974
#define MENU_VIEW_DISPLAYVMSPEED        975
#define MENU_VIEW_MOUSEANDKEYBOARDSETUP 976
#define MENU_VIEW_SCRIPTFOLDER          977
#define PROGRESS_FIRMWARE               980
#define PICTURE_FIRMWARE                990
#define RICHEDIT_CODE_INPUT             1000
#define RICHEDIT_CODE_OUTPUT            1001
#define RICHEDIT_MAIN_OUTPUT            1002
#define COMBOBOXEX_MKSETTINGS_CONFIG    2000
#define COMBOBOXEX_MKSETTINGS_GAMEPROFILE 2001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40140
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
