//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Zen++.rc
//
#define ACCELERATOR_ZENPP               100
#define MENU_RICHEDIT_POPUP             110
#define FILE_ZPPUPDATER                 117
#define DIALOG_FIRMWARE                 118
#define BITMAP_FIRMWARE_STEP1           120
#define BITMAP_FIRMWARE_STEP2           121
#define FILE_FIRMWARE_COMPATIBLE        122
#define FILE_FIRMWARE_LATEST            123
#define ICON_ZENPP                      200
#define DIALOG_MAIN                     300
#define DIALOG_ABOUT                    301
#define MENU_MAIN                       400
#define EDIT_ABOUT_INFORMATION          1000
#define EDIT_MAIN_SLOTS                 1001
#define BUTTON_FIRMWARE_NEXT            1011
#define BUTTON_FIRMWARE_CANCEL          1012
#define LABEL_FIRMWARE_INSTRUCTIONS     1013
#define PICTURE_FIRMWARE                1014
#define LABEL_FIRMWARE_STATUS           1015
#define PROGRESS_FIRMWARE               1016
#define BUTTON_FIRMWARE_BACK            1017
#define LABEL_FIRMWARE_STEP             1018
#define EDIT_FIRMWARE_DESCRIPTORS       1019
#define LABEL_ABOUT_HEADER              1100
#define LABEL_ABOUT_VERSIONINFO         1101
#define LIST_MAIN_SLOTS                 1200
#define BUTTON_ABOUT_OK                 1300
#define BUTTON_MAIN_ADDSCRIPT           1301
#define BUTTON_MAIN_REMOVESELECTION     1302
#define BUTTON_MAIN_ERASEALLSCRIPTS     1303
#define BUTTON_MAIN_FACTORYRESET        1304
#define BUTTON_MAIN_SOFTRESET           1305
#define BUTTON_MAIN_PROGRAMDEVICE       1306
#define RICHEDIT_MAIN_OUTPUT            1400
#define MENU_VIEW_BINLIB                40082
#define MENU_VIEW_INPUTMONITOR          40084
#define MENU_CONNECTION_RECONNECT       40087
#define MENU_CONNECTION_DISCONNECT      40088
#define MENU_HELP_CHANGELOG             40090
#define MENU_HELP_NEWS                  40091
#define MENU_VIEW_DEVICEMONITOR         40092
#define MENU_VIEW_CONNECTIONTRACE       40094
#define MENU_CONNECTION_CONNECTONSTARTUP 40096
#define MENU_VIEW_BLACKBACKGROUND       40099
#define MENU_DEVICE_LOAD_AND_RUN        40100
#define MENU_VIEW_24HOURTIMESTAMPS      40100
#define MENU_DEVICE_PROGRAM_DEVICE      40101
#define MENU_DEVICE_CLEARBLUETOOTHDEVICES 40102
#define MENU_VIEW_MOUSEANDKEYBOARDSETUP 40102
#define MENU_DEVICE_PROGRAMDEVICE       40103
#define MENU_DEVICE_LOADANDRUN          40104
#define MENU_DEVICE_CYCLESLOTS          40105
#define MENU_DEVICE_REMOTEPLAY          40106
#define MENU_DEVICE_TURNOFFCONTROLLER   40107
#define MENU_DEVICE_PS4SPECIALTY        40108
#define MENU_DEVICE_REFRESHATTACHEDDEVICES 40109
#define MENU_DEVICE_EOP_AUTO            40110
#define MENU_DEVICE_EOP_NINTENDOSWITCH  40111
#define MENU_DEVICE_EOP_PLAYSTATION3    40112
#define MENU_DEVICE_EOP_PLAYSTATION4    40113
#define MENU_DEVICE_EOP_PLAYSTATION5    40114
#define MENU_DEVICE_EOP_PCMOBILEXBOX360 40115
#define MENU_DEVICE_EOP_XBOXONEX        40116
#define MENU_DEVICE_OM_NORMAL           40117
#define MENU_DEVICE_OM_TOURNAMENT       40118
#define MENU_DEVICE_OM_WHEEL            40119
#define MENU_DEVICE_RSC_DISABLED        40120
#define MENU_DEVICE_RSC_PSL3            40121
#define MENU_DEVICE_RSC_PSSHARE         40122
#define MENU_FILE_EXIT                  40123
#define MENU_FIRMWARE_COMPATIBLE        40124
#define MENU_FIRMWARE_CUSTOM            40125
#define MENU_FIRMWARE_LATEST            40126
#define MENU_FIRMWARE_ERASE             40127
#define MENU_HELP_ABOUT                 40128
#define MENU_HELP_ZENPPNEWS             40129
#define MENU_POPUP_COPY                 40130
#define MENU_POPUP_SELECTALL            40131
#define MENU_POPUP_CLEAR                40132

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40108
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
